name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIST_DIR: "./dist/build/uBlock0.chromium"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Version and Filename Env Vars
        run: |
          echo "TAG=$(cat dist/version)" >> $GITHUB_ENV
          echo "CRX_FILENAME=uBlock0_$(cat dist/version).crx" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build uBlock Origin for Chromium
        run: make chromium

      - name: Patch update URL in manifest.json
        run: |
          MANIFEST_PATH="${{ env.DIST_DIR }}/manifest.json"
          # Use temp file to avoid issues with in-place editing
          jq --arg url "${{ vars.PAGES_URL }}/update.xml" '.update_url = $url' "$MANIFEST_PATH" > tmp.$$.json && mv tmp.$$.json "$MANIFEST_PATH"

      - name: Build .crx file
        env:
          CRX3_PRIVATE_KEY: ${{ secrets.CRX3_PRIVATE_KEY }}
        run: |
          echo "$CRX3_PRIVATE_KEY" | npx crx3@1.1.3 -p /dev/stdin -o "${{ env.CRX_FILENAME }}" "${{ env.DIST_DIR }}/"

      - name: Generate update.xml
        run: |
          CRX_URL="${{ vars.PAGES_URL }}/${{ env.CRX_FILENAME }}"
          cat <<EOF > update.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='${{ vars.CRX3_ID }}'>
              <updatecheck codebase='${CRX_URL}' version='${{ env.TAG }}' />
            </app>
          </gupdate>
          EOF

      - name: Prepare for deployment
        run: |
          mkdir -p _site
          cp .github/index.html _site/index.html
          mv "${{ env.CRX_FILENAME }}" update.xml _site/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
